**Упражнение 1. Записать следующие команды (каждую в своей ячейке).**

In [1]:
2*3

6

In [2]:
k=3+4
print(k)

7


In [3]:
(k+1)*(k-1)

48

In [4]:
(x+1)*(x-1)

NameError: name 'x' is not defined

**Упражнение 3.**

**1) Убрать из рабочего пространства все переменные.**

In [5]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


**2) Ввести переменные x, y, z, t, задав им значения соответственно 1, 2, 3, 4.**

In [6]:
x=1
y=2
z=3
t=4

**3) Вывести в командное окно информацию обо всех переменных.**

In [7]:
%whos

Variable   Type    Data/Info
----------------------------
t          int     4
x          int     1
y          int     2
z          int     3


**4) Удалить из рабочего пространства переменную x.**

In [8]:
del(x)

**5) Вывести в командное окно информацию об оставшихся переменных.**

In [9]:
%whos

Variable   Type    Data/Info
----------------------------
t          int     4
y          int     2
z          int     3


**Упражнение 4.**

**1) Задать какую-нибудь матрицу R размерностью 3x4. Отобразить её
сначала в текстовой ячейке в режиме Markdown. Затем ввести её в кодовой
ячейке с помощью модуля numpy.**

$\begin{bmatrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \end{bmatrix}$

In [10]:
import numpy as np

In [12]:
R = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(R)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**2) Заменить значения элемента R(2,3) на противоположный (R(2,3)= -R(2,3)), вывести обновленную матрицу R в командное окно.**

In [13]:
R[2, 3] = -R[2,3]
print(R)

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11 -12]]


**Уменьшить на 4 элемент, стоящий в первой строке и третьем столбце, вывести обновленную матрицу R в командное окно.**

In [14]:
R[0, 2] = R [0,2] - 4
print(R)

[[  1   2  -1   4]
 [  5   6   7   8]
 [  9  10  11 -12]]


**Удвоить все элементы второго столбца.**

In [15]:
R[:,1]=R[:,1]*2
print(R)

[[  1   4  -1   4]
 [  5  12   7   8]
 [  9  20  11 -12]]


**Утроить все элементы первой строки.**

In [16]:
R[0,:]=R[0,:]*3
print(R)

[[  3  12  -3  12]
 [  5  12   7   8]
 [  9  20  11 -12]]


**3) Задать векторы-строки размерности 1x5 и 1x7**

In [17]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([1, 2, 3, 4, 5, 6, 7])

**Задать 3 вектора-столбца разной размерности.**

In [18]:
s1 = np.array([[1], [2], [3]])
s2 = np.array([[1], [2], [3], [4]])
s3 = np.array([[1], [2], [3], [4], [5]])

**Упражнение 5.**

In [20]:
import numpy as np
import numpy.matlib

**1) Ввести матрицы.**

In [21]:
A=np.array([[1,2,3], [4,5,6]])
B=np.array([[1,-2,1], [-2,3,4]])
C=np.array([2])
D=np.matlib.ones((2,3))
E=np.matlib.eye(3,3)

**2) Выполнить операции (или убедиться, что их выполнить нельзя):**

In [22]:
A+B

array([[ 2,  0,  4],
       [ 2,  8, 10]])

In [23]:
A+C

array([[3, 4, 5],
       [6, 7, 8]])

In [24]:
A+E

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [25]:
A-B

array([[0, 4, 2],
       [6, 2, 2]])

In [26]:
A-C

array([[-1,  0,  1],
       [ 2,  3,  4]])

C*A

In [28]:
np.matmul(A,B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [29]:
B=B.transpose()
np.matmul(A,B)

array([[ 0, 16],
       [ 0, 31]])

**Упражнение 7. Вычислить значения с помощью задания данных в виде вектора.**

In [30]:
vec=np.array([1, 3, 5])
np.sqrt(vec)

array([1.        , 1.73205081, 2.23606798])

**Упражнение С1.**

**1) Задать вектор-строку с элементами от -2 до 10 с шагом 2, утроить все ее элементы.**

In [37]:
vec = np.arange(-2, 11, 2)
print(vec)

[-2  0  2  4  6  8 10]


In [38]:
vec*=3
print(vec)

[-6  0  6 12 18 24 30]


**2) Задать вектор-строку с элементами от 45 до 5 с шагом -5, определить ее размерность.**

In [40]:
vec = np.arange(45, 4, -5)
print(len(vec))

9


**Упражнение С2.**

**1) Вычислить значения cos(x). То же для остальных тригонометрических функций (использовать значение np.pi).**

In [42]:
trig = [0, np.pi/6, np.pi/3, np.pi/2, (2*np.pi)/3, (5*np.pi)/6, np.pi, (7*np.pi)/6, (4*np.pi)/3, (3*np.pi)/2, (5*np.pi)/3, (11*np.pi)/6, 2*np.pi]

In [66]:
print(np.cos(trig))

[ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01
 -5.00000000e-01 -1.83697020e-16  5.00000000e-01  8.66025404e-01
  1.00000000e+00]


In [67]:
print(np.sin(trig))

[ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01
 -2.44929360e-16]


In [65]:
print(np.tan(trig))

[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16  5.77350269e-01
  1.73205081e+00  5.44374645e+15 -1.73205081e+00 -5.77350269e-01
 -2.44929360e-16]


**2) Вычислить значение выражения.**

In [64]:
x = np.arange(-2, 2.5, 0.5) 

In [69]:
print(np.cosh(x)**2-np.sinh(x)**2)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


**3) Повторить теоретический материал, ответить на контрольные вопросы:**

**3.1) Какие имена переменных являются допустимыми?**

*В именах переменных можно использовать латинские буквы, цифры и символ подчеркивания; большие и малые буквы в именах различаются; имя должно начинаться с буквы; длина имени не должна превышать 63 символа.*

**3.2) Каким образом можно получить информацию о переменных рабочего пространства?**

*Информацию о переменных можно получить с помощью команды “%whos”.*

**3.3) Каким образом можно получить подробную информацию о функции или команде?**

*Подробную информацию можно получить командой help и именем интересующей функции или команды.*

**3.4) Как задать матрицу произвольной размерности?**

*Функцией A.reshape(n,k) Превратит массив A в матрицу размерности n на k.*

**3.5) Каким образом осуществляются поэлементные арифметические действия с матрицами одинаковой размерности?**

*Поэлементные арифметические действия выполняются с соответствующими элементами матриц одинаковой размерности.*