In [97]:
import numpy as np
import sympy

**Упражнение 2.1. Вычислить определители второго порядка, обращаясь через индексы к элементам массива, и сделать проверку с помощью функции det. Буквенные выражения необходимо задать в символьном виде.**

In [7]:
a,b=symbols('a b')

**2.1.1**

In [8]:
v=Matrix([[-1, 4],[-5, 2]])

In [9]:
detV = v[0,0] * v[1, 1] - v[0, 1] * v[1, 0]

In [10]:
print(detV)
print(det(v))

18
18


**2.1.2**

In [11]:
v2=Matrix([[a+b, a-b],[a+b, a-b]])

In [12]:
detV2 = v2[0,0] * v2[1, 1] - v2[0, 1] * v2[1, 0]

In [13]:
print(detV2)
print(det(v2))

0
0


**2.1.3**

In [15]:
v3=Matrix([[x, x+1],[-4, x+1]])

NameError: name 'x' is not defined

Так как x не задан, выходит ошибка.

In [34]:
x=symbols('x')

In [17]:
v3=Matrix([[x, x+1],[-4, x+1]])

In [18]:
detV3 = v3[0,0] * v3[1, 1] - v3[0, 1] * v3[1, 0]

In [19]:
print(detV3)
print(det(v3))

x*(x + 1) + 4*x + 4
x**2 + 5*x + 4


**Упражнение 2.2. Вычислить определители третьего порядка с помощью функции det.**

**2.2.1**

In [22]:
v1=Matrix([[1, 2, 3],[4, 5, 6], [7,8,1]])

In [23]:
print(det(v1))

24


**2.2.2**

In [24]:
v2=Matrix([[3, 4, -5],[8, 7, -2], [2,-1,8]])

In [25]:
print(det(v2))

0


**2.2.3**

In [26]:
a, b, c, x=symbols('a b c x')

In [27]:
v3=Matrix([[a+x, x, x],[x, b+x, x], [x,x,c+x]])

In [28]:
print(det(v3))

a*b*c + a*b*x + a*c*x + b*c*x


**2.2.4**

In [29]:
import math
a, b, c = symbols('a b c')

In [32]:
v4=Matrix([[sin(a), cos(a), 1],[sin(b), cos(b), 1], [sin(c),cos(c),1]])

In [35]:
print(det(v4))

sin(a)*cos(b) - sin(a)*cos(c) - sin(b)*cos(a) + sin(b)*cos(c) + sin(c)*cos(a) - sin(c)*cos(b)


**Упражнение 2.3. Решить системы уравнений по формулам Крамера. Сделать проверку.**

**2.3.1**

In [71]:
A = np.matrix ('3 -5; 2 7')
B = np.matrix ('13; 81')

Проверка применимости формул Крамера.

In [72]:
A_det = np.linalg.det(A)
print(A_det != 0)

True


In [73]:
X_m = np.matrix(A)
X_m[:, 0] = B
Y_m = np.matrix(A)
Y_m[:, 1] = B

x=np.linalg.det(X_m)/A_det
y=np.linalg.det(Y_m)/A_det

print(x, y)

16.000000000000007 7.000000000000001


Проверка

In [77]:
X = np.matrix ('16; 7')
print(np.dot(A, X)-B==0)

[[ True]
 [ True]]


*Ответ: (16, 7).*

**2.3.2**

In [78]:
A = np.matrix ('3 -4; -6 8')
B = np.matrix ('-6; 12')

Проверка применимости формул Крамера.

In [81]:
A_det = np.linalg.det(A)
print(A_det != 0)

False


*Формулы Крамера неприменимы.*

**2.3.3**

In [142]:
A = np.matrix ('7 2 3; 5 -3 2; 10 -11 5')
B = np.matrix ('15; 15; 36')

Проверка применимости формул Крамера.

In [87]:
A_det = np.linalg.det(A)
print(A_det != 0)

True


In [88]:
X_m = np.matrix(A)
X_m[:, 0] = B
Y_m = np.matrix(A)
Y_m[:, 1] = B
Z_m = np.matrix(A)
Z_m[:, 2] = B

x=np.linalg.det(X_m)/A_det
y=np.linalg.det(Y_m)/A_det
z=np.linalg.det(Z_m)/A_det

print(x, y, z)

1.999999999999998 -1.0 0.999999999999999


Проверка

In [89]:
X = np.matrix ('2; -1; 1')
print(np.dot(A, X)-B==0)

[[ True]
 [ True]
 [ True]]


*Ответ: (2, -1, 1).*

**2.3.4**

In [91]:
A = np.matrix ('2 1 0; 1 0 3; 0 5 -1')
B = np.matrix ('5; 16; 10')

Проверка применимости формул Крамера.

In [92]:
A_det = np.linalg.det(A)
print(A_det != 0)

True


In [93]:
X_m = np.matrix(A)
X_m[:, 0] = B
Y_m = np.matrix(A)
Y_m[:, 1] = B
Z_m = np.matrix(A)
Z_m[:, 2] = B

x=np.linalg.det(X_m)/A_det
y=np.linalg.det(Y_m)/A_det
z=np.linalg.det(Z_m)/A_det

print(x, y, z)

1.0 3.000000000000001 5.000000000000001


Проверка

In [94]:
X = np.matrix ('1; 3; 5')
print(np.dot(A, X)-B==0)

[[ True]
 [ True]
 [ True]]


*Ответ: (1, 3, 5).*

**Упражнение 2.4. Решить системы уравнений упражнения 2.3(1) и 2.3(3) в библиотеке Sympy. Сделать проверку.**

**2.4.1 (2.3.1)**

In [98]:
A = sympy.Matrix ([[3, -5], [2, 7]])
B = sympy.Matrix ([[13], [81]])

Проверка применимости формул Крамера.

In [99]:
A_det = sympy.det(A)
print(A_det != 0)

True


In [101]:
X_m = sympy.Matrix(A)
X_m[:, 0] = B
Y_m = sympy.Matrix(A)
Y_m[:, 1] = B

x=sympy.det(X_m)/A_det
y=sympy.det(Y_m)/A_det

print(x, y)

16 7


Проверка

In [108]:
X = sympy.Matrix ([[16], [7]])
print(A*X-B)

Matrix([[0], [0]])


*Ответ: (16, 7).*

**2.4.2 (2.3.3)**

In [115]:
A = sympy.Matrix ([[7, 2, 3], [5, -3, 2], [10, -11, 5]])
B = sympy.Matrix ([[15], [15], [36]])

Проверка применимости формул Крамера.

In [116]:
A_det = sympy.det(A)
print(A_det != 0)

True


In [119]:
X_m = sympy.Matrix(A)
X_m[:, 0] = B
Y_m = sympy.Matrix(A)
Y_m[:, 1] = B
Z_m = sympy.Matrix(A)
Z_m[:, 2] = B

x=sympy.det(X_m)/A_det
y=sympy.det(Y_m)/A_det
z=sympy.det(Z_m)/A_det

print(x, y, z)

2 -1 1


Проверка

In [120]:
X = sympy.Matrix ([[2], [-1], [1]])
print(A*X-B)

Matrix([[0], [0], [0]])


*Ответ: (2, -1, 1).*

**Упражнение 2.5. Решить системы уравнений из упражнений 2.3, используя обратную матрицу.**

**2.5.1 (2.3.1)**

In [129]:
A = np.matrix ('3 -5; 2 7')
B = np.matrix ('13; 81')

Проверка применимости формул Крамера.

In [130]:
A_det = np.linalg.det(A)
print(A_det != 0)

True


In [123]:
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)

[[16.]
 [ 7.]]


*Ответ (16, 7).*

**2.5.2 (2.3.2)**

In [131]:
A = np.matrix ('3 -4; -6 8')
B = np.matrix ('-6; 12')

Проверка применимости формул Крамера.

In [132]:
A_det = np.linalg.det(A)
print(A_det != 0)

False


*Формулы Крамера неприменимы.*

**2.5.3 (2.3.3)**

In [135]:
A = np.matrix ('7 2 3; 5 -3 2; 10 -11 5')
B = np.matrix ('15; 15; 36')

Проверка применимости формул Крамера.

In [136]:
A_det = np.linalg.det(A)
print(A_det != 0)

True


In [137]:
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)

[[ 2.]
 [-1.]
 [ 1.]]


*Ответ (2, -1, 1).*

**2.5.4 (2.3.4)**

In [139]:
A = np.matrix ('2 1 0; 1 0 3; 0 5 -1')
B = np.matrix ('5; 16; 10')

Проверка применимости формул Крамера.

In [140]:
A_det = np.linalg.det(A)
print(A_det != 0)

True


In [141]:
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)

[[1.]
 [3.]
 [5.]]


*Ответ (1, 3, 5).*